mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import problems.urls
import users.urls
import status.urls
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('user/', include(users.urls)),
    path('status/',include(status.urls)),
    path('admin/', admin.site.urls),
    path('problems/', include(problems.urls)),
    path('captcha/', include('captcha.urls')),
    path('contact_us/', views.contact_us, name='contact_us'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/13

from django.contrib import admin
from django.urls import path, include
import problems.views
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user_info, name='user_info'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgetpassword/', views.forget_password, name='forgetpassword'),
    path('resetpassword/<str:active_code>', views.reset_password, name='resetpassword'),
    path('terms/', views.terms, name='terms'),
    path('register/check_email/', views.check_email, name='check_email'),
    path('register/check_user/', views.check_user, name='check_user'),
    path('register/check_captcha/', views.check_captcha, name='check_captcha'),
    path('logout/', views.logout, name='logout'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('reset_pwd2/', views.reset_pwd2, name='reset_pwd2'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile')


class EmailVerifyRecord(models.Model):
    """邮箱激活码"""
    code = models.CharField(max_length=20, verbose_name='验证码')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    send_type = models.CharField(verbose_name='验证码类型', choices=(('register', '注册'), ('forget', '忘记密码')),
                                 max_length=20)
    send_time = models.DateTimeField(verbose_name='发送时间', auto_now_add=True)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)

users/forms.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/14
from django import forms
from django.contrib.auth.models import User
from django.contrib import auth
from captcha.fields import CaptchaField
import re


def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class RegistrationForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=50)
    email = forms.EmailField(label='邮箱')
    password1 = forms.CharField(label='密码',
                                required=True,
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='请再次输入密码',
                                required=True,
                                widget=forms.PasswordInput)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username)>50:
            raise forms.ValidationError('用户名太长了')
        else:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('用户名已经存在')

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email_check(email):
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError('此邮箱已经注册')
        else:
            raise forms.ValidationError('请输入正确的邮箱')
        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 6:
            raise forms.ValidationError('密码太短了')
        elif len(password1) > 16:
            raise forms.ValidationError('密码太长了')
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('两次输入不一样，请重新输入')
        return password2


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名',
                               required=True,
                               max_length=50,
                               widget=forms.TextInput(attrs={
                                   'placeholder': '请输入用户名',
                               }))
    password = forms.CharField(label='密码',
                               required=True,
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': '请输入密码',
                               }))
    # captcha = CaptchaField(error_messages={'invalid': '验证码错误'})

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class ForgetPasswordForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=50)
    email = forms.EmailField(label='邮箱')
    captcha = CaptchaField(label='验证码', error_messages={'invalid': '验证码错误'})

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if not User.objects.filter(email=email, username=username).exists():
            raise forms.ValidationError('用户名或邮箱错误')

        return self.cleaned_data


class ResetPassword(forms.Form):
    password1 = forms.CharField(required=True,
                                label='密码',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(required=True,
                                label='请再次输入密码密码',
                                widget=forms.PasswordInput)

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 6:
            raise forms.ValidationError('密码太短了')
        elif len(password1) > 16:
            raise forms.ValidationError('密码太长了')
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('两次输入不一样，请重新输入')
        return password2

users/views.py
import time
from datetime import timedelta, datetime

from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore
from django.contrib.auth import authenticate
from django.db import connection
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect
from random import Random

from django.utils.timezone import now

from problems.models import Category
from .forms import LoginForm, RegistrationForm, ForgetPasswordForm, ResetPassword
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.models import User
from .utils.email_send import send_email
from .models import EmailVerifyRecord
from django.contrib.auth.hashers import make_password
from status.models import Status
# Create your views here.


def user_info(request):
    '''
    查看用户信息
    '''
    if request.user.is_authenticated:
        # 提交总数和ac总数
        submission_num = Status.objects.filter(user=request.user).count()
        ac_num = Status.objects.filter(user=request.user).values('problem__slug').distinct().count()

        # 各个分类对应的做题数和ac数
        category_x_list = []
        category_y_submit_list = []
        category_y_ac_list = []
        category_list = Category.objects.all()
        for category in category_list:
            category_x_list.append(category.title)
            category_y_submit_list.append(Status.objects.filter(user=request.user,problem__category=category).count())
            category_y_ac_list.append(Status.objects.filter(user=request.user,
                                                            problem__category=category, is_first_ac=True).count())
        # 判断是返回一个月的数据还是从第一次提交开始算起
        nowadays = datetime.now()
        a_month = datetime.now() - timedelta(days=30)

        if Status.objects.filter(user=request.user,is_first_submit=True).exists():
            first_submit_time = Status.objects.get(user=request.user,is_first_submit=True).submit_time
            if first_submit_time>a_month:
                a_month=first_submit_time

        # 最近一个月的题目或者从第一次提交到现在的题目
        select = {'day': 'date(submit_time)'}
        count_data = Status.objects. \
            filter(submit_time__range=(a_month, nowadays),user=request.user). \
            extra(select=select).\
            values('day').order_by("day").annotate(number=Count('submit_time'))
        submit_x_list = []
        submit_y_list = []
        ac_y_list = []
        ac_x_list = []
        for i in count_data:
            print(type(i['day']))
            submit_x_list.append(str(i['day']))
            submit_y_list.append(i['number'])
        count_data = Status.objects. \
            filter(submit_time__range=(a_month, nowadays), user=request.user,is_first_ac=True). \
            extra(select=select).values('day').order_by("day").annotate(number=Count('submit_time'))
        for i in count_data:
            ac_x_list.append(str(i['day']))
            ac_y_list.append(i['number'])
        submit_index=0
        ac_index=0
        submit_x=[]
        submit_y=[]
        ac_y=[]
        for i in range((nowadays - a_month).days + 1):
            day = (a_month + timedelta(days=i)).strftime("%Y-%m-%d")
            submit_x.append(day)
            if day in submit_x_list:
                submit_y.append(submit_y_list[submit_index])
                submit_index+=1
            else:
                submit_y.append(0)
            if day in ac_x_list:
                ac_y.append(ac_y_list[ac_index])
                ac_index+=1
            else:
                ac_y.append(0)

        context = {
            'submission_num': submission_num,
            'AC_num': ac_num,
            'submit_x_list': submit_x,
            'submit_y_list': submit_y,
            'AC_y_list': ac_y,
            'category_x': category_x_list,
            'category_y_submit': category_y_submit_list,
            'category_y_AC': category_y_ac_list,
        }
        return render(request, 'user_info.html', context)
    else:
        return render(request, 'home.html', {})


def forget_password(request):
    if request.method == 'GET':
        form = ForgetPasswordForm()
    if request.method == 'POST':
        form = ForgetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            send_email(email, 'forget')
            return render(request, 'send_success.html')
    return render(request, 'forget_password.html', {'form': form})


def reset_password(request, active_code):
    if request.method == 'GET':
        record = EmailVerifyRecord.objects.filter(code=active_code)
        if record:
            for item in record:
                email = item.email
                demo = User.objects.filter(email=email)
                if demo:
                    context = {
                        'email': email,
                        'form': ResetPassword(),
                        'code': active_code,
                    }
                    return render(request, 'reset_password.html', context=context)
        return redirect('home')
    else:
        form = ResetPassword(request.POST)
        print(333)
        if form.is_valid():
            print(1222)
            password2 = form.cleaned_data['password2']
            email = request.POST.get('email')
            print(email)
            user = User.objects.get(email=email)
            user.password = make_password(password=password2)
            user.save()
            print(155)
            return redirect('home')
        else:
            return redirect('home')


def login(request):
    if request.is_ajax():
        user_name = request.POST.get("username", "")
        pass_word = request.POST.get("password", "")
        user = authenticate(username=user_name, password=pass_word)
        if user is not None:
            auth.login(request, user)
            return JsonResponse({"status": "success"})
        return JsonResponse({"status": "error"})
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return redirect(request.GET.get('from', reverse('home')))

    return render(request, 'login.html', {})


def logout(request):
    auth.logout(request)
    return redirect(request.GET.get('from', reverse('home')))


def register(request):
    if request.method == 'POST':
        register_form = RegistrationForm(request.POST)
        print('进入post')
        if register_form.is_valid():
            print('进入form')
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password1']
            email = register_form.cleaned_data['email']
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))

    key = CaptchaStore.generate_key()
    image_url = captcha_image_url(key)
    context = {
        'key': key,
        'image_url': image_url,
    }
    return render(request, 'register.html', context)


def terms(request):
    '''
    服务条款
    :param request:
    :return:
    '''
    return render(request, 'terms.html', {})


def check_user(request):
    res = {}
    username = request.GET.get('username')
    print(username)
    if username:
        if User.objects.filter(username=username).exists():
            print('用户名存在')
            res = {"code": 100, "msg": "用户名存在，请重新输入"}
        else:
            res = {"code": 101}
    else:
        res = {"code": 102, "msg": "请输入用户名"}

    return JsonResponse(res)


def check_captcha(request):
    print('检查验证码')
    res = {}
    captcha_0 = request.GET.get('captcha_0')
    captcha_1 = request.GET.get('captcha_1')
    if captcha_1:
        if CaptchaStore.objects.filter(response=captcha_1, hashkey=captcha_0):
            print('验证码正确')
            res = {"code": 101}
        else:
            res = {"code": 100, "msg": "验证码错误，请重新输入"}
    else:
        res = {"code": 102, "msg": "请输入验证码"}

    return JsonResponse(res)


def check_email(request):
    res = {}
    email = request.GET.get('email')
    if email:
        if User.objects.filter(email=email).exists():
            res = {"code": 100, "msg": "该邮箱已经注册，请重新输入"}
        else:
            res = {"code": 101}
    else:
        res = {"code": 102, "msg": "请输入邮箱"}

    return JsonResponse(res)


def questionnaire(request):
    return render(request, 'questionnaire.html')


def reset_pwd2(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            password = request.POST['new_password1']
            if password == '':
                render(request, 'reset_password2.html')
            request.user.set_password(password)
            request.user.save()
            auth.authenticate(username=request.user.username, password=password)
            auth.login(request, request.user)
            return redirect(request.GET.get('from', reverse('home')))
        return render(request, 'reset_password2.html')
    else:
        return render(request,'home.html',{})

users/templates/find_password.html
{% extends 'base.html' %}
{% block title %}
    找回密码
{% endblock %}
{% block content %}


{% endblock %}

users/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    登录
{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static 'user/js.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }}
            {{ field }}
        {% endfor %}
    <input type="submit" value="确认发送邮件">
    </form>

{% endblock %}

users/templates/login.html
{% extends 'base_deputy.html' %}
{% load static %}
{% block title %}
    登录
{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static 'user/js.js' %}"></script>
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

{% endblock %}

{#{% extends "base_deputy.html" %}#}


{% block content %}
    <section id="login_box" class="mt-3">
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image row d-flex justify-content-center">
                        <figure><img src="{% static 'user/images/signin-image.jpg' %}" alt="sing up image"></figure>
                        <div class="row">
                            <a href="{% url 'user:register' %}" class="signup-image-link text-info">申请一个账号</a>
                            <span class="text-black-50 ml-3 mr-3">or</span>
                            <a href="{% url 'home' %}" class="signup-image-link text-info">返回主页面</a>
                        </div>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">登陆</h2>
                        <form method="POST" class="register-form" id="login-form" action="{% url 'user:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="your_name" placeholder="请输入用户名"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="your_pass" placeholder="请输入密码"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term"/>
                                <label for="remember-me" class="label-agree-term text-muted"><span><span></span></span>记住我</label>
                                <span class="offset-6"><a href="{% url 'user:forgetpassword' %}">忘记密码?</a></span>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="登陆"/>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label text-muted">第三方登陆</span>
                            <ul class="socials">
                                <li class="col-6 pl-2 pr-2">
                                    <a href="#">
                                        <img width="25" src="{% static 'user/images/QQ-icon.png' %}" alt="">
                                        <span class="row d-flex align-items-center justify-content-center">QQ</span>
                                    </a>
                                </li>
                                <li class="col-6 pl-2 pr-2">
                                    <a href="#">
                                        <img width="25" src="{% static 'user/images/WeChat-icon.png' %}" alt="">
                                        <span class="row d-flex align-items-center justify-content-center">微信</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

users/templates/reset_password.html
{% extends 'base.html' %}
{% block title %}
    找回密码
{% endblock %}
{% block content %}

    <form method="post" action="{% url 'user:resetpassword' active_code=code %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" value="{{ email }}" name='email'>
        <input type="submit" value="确认">
    </form>
{% endblock %}

users/templates/reset_password2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    修改密码
{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static 'user/js/reset_password_js.js' %}"></script>
    <link rel="stylesheet" href="{% static 'user/css/reset_password2.css' %}">
        <style type="text/css">
        small.error_tip{
            color: #e90b03;
            display: none;
        }
    </style>
{% endblock %}
{% block content %}
    <form method="post">
        <div class="container bg-white mt-sm-4 mb-5">
            <div class="wrapper d-flex justify-content-center flex-column px-md-5 px-1">
                <div class="h3 text-center font-weight-bold">修改密码</div>
                <form method="post" action="{% url 'user:reset_pwd2' %}" id="reset_password_form">
                    {% csrf_token %}
                    <div class="row my-4 offset-3">
                        <div class="col-md-6"><label>用户名</label>
                            <input type="text" placeholder="{{ user.username }}" ></div>
                    </div>
                    <div class="row my-4 offset-3">
                        <div class="col-md-6 pt-md-0 pt-4"><label>旧密码</label>
                            <input type="password" placeholder="请输入旧密码">
                        </div>
                    </div>
                    <div class="row my-md-4 my-2 offset-3">
                        <div class="col-md-6"><label>新密码</label>
                            <input type="password" placeholder="请输入新密码" id="new_password1" name="new_password1">
                            <small class="error_tip">提示信息</small>
                        </div>
                    </div>
                    <div class="row my-md-4 my-2 offset-3">
                        <div class="col-md-6 pt-md-0 pt-4"><label>确认新密码</label>
                            <input type="password" placeholder="请再次输入新密码" id="new_password2" name="new_password2">
                            <small class="error_tip">提示信息</small>
                        </div>

                    </div>
                </form>
                <div class="d-flex justify-content-end">
                    <!-- 弹出 忘记旧密码？ 模态框 -->
                    <button type="button" class="btn-sm m-4 btn-forget" style="border: 0px" data-toggle="modal"
                            data-target="#forget_old_pwd">忘记旧密码？
                    </button>
                    <button class="btn m-3" id="btn_submit">提交</button>
                </div>
            </div>
        </div>
    </form>
    <!-- 服务条款 模态框 -->
    <div class="modal fade" id="forget_old_pwd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">忘记旧密码?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- 模态框body begin -->
                    <p>
                        请退出登陆后，在登陆页面点击「忘记密码？」，使用绑定的邮箱进行身份验证后方可更改密码
                    </p>
                    <p class="text-muted small">
                        后端攻城狮把这个跳转写死了，只能没登录的时候访问，我只是一个前端画画的，我有什么办法呢(╥╯^╰╥)
                    </p>
                    <!-- 模态框body end -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/send_success.html
{% extends 'base.html' %}
{% block title %}
    邮件发出成功
{% endblock %}
{% block content %}
    <p>发送成功</p>
{% endblock %}

users/templates/terms.html
{% extends 'base.html' %}
{% block title %}
    声明
{% endblock %}
{% block content %}
    巴拉巴拉巴拉
{% endblock %}