mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import problems.urls
import users.urls
import status.urls
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('user/', include(users.urls)),
    path('status/',include(status.urls)),
    path('admin/', admin.site.urls),
    path('problems/', include(problems.urls)),
    path('captcha/', include('captcha.urls')),
    path('contact_us/', views.contact_us, name='contact_us'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

problems/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/11

from django.urls import path
from . import views
app_name = 'problem'
urlpatterns = [
    path('', views.problems, name='problem_list'),
    path('<slug:slug>/', views.problem_detail, name='problem_detail'),
    path('category',views.problem_all_category, name='problem_all_category'),
    path('category/<slug:slug>', views.problem_category, name='problem_category'),
    path('modify_category_difficulty', views.modify_category_difficulty, name='modify_category_difficulty'),
    path('recommend', views.problem_recommend, name='problem_recommend'),
    path('problem_add', views.problems_add, name='problem_add'),
]

users/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/13

from django.contrib import admin
from django.urls import path, include
import problems.views
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user_info, name='user_info'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgetpassword/', views.forget_password, name='forgetpassword'),
    path('resetpassword/<str:active_code>', views.reset_password, name='resetpassword'),
    path('terms/', views.terms, name='terms'),
    path('register/check_email/', views.check_email, name='check_email'),
    path('register/check_user/', views.check_user, name='check_user'),
    path('register/check_captcha/', views.check_captcha, name='check_captcha'),
    path('logout/', views.logout, name='logout'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('reset_pwd2/', views.reset_pwd2, name='reset_pwd2'),
]

problems/models.py
from django.db import models
from datetime import datetime
from uuslug import slugify
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='类型')
    content = models.TextField(verbose_name='介绍', default='')
    vote_number = models.IntegerField(default=1, verbose_name="投票数")
    slug = models.SlugField(editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)


class SimpleCategory(models.Model):
    title = models.CharField(max_length=255, verbose_name='类型')
    vote_number = models.IntegerField(default=1, verbose_name="投票数")
    problem = models.ForeignKey("Problem",on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Problem(models.Model):
    slug = models.SlugField(editable=False)
    problem_id = models.CharField(max_length=20, verbose_name='题目编号')
    time_limit = models.IntegerField(default=1000, verbose_name='时间限制')
    memory_limit = models.IntegerField(default=65536, verbose_name='内存限制')
    title = models.CharField(max_length=1000, verbose_name='题目标题', blank=True)
    description = models.TextField(verbose_name='题目描述', blank=True)
    input_description = models.TextField(verbose_name='输入描述', blank=True)
    output_description = models.TextField(verbose_name='输出描述', blank=True)
    sample_input = models.TextField(verbose_name='样例输入', blank=True)
    sample_output = models.TextField(verbose_name='样例输出', blank=True)
    hint = models.TextField(blank=True, verbose_name='题目提示')
    source = models.CharField(max_length=200, blank=True, verbose_name='题目来源')
    source_url = models.URLField(verbose_name='题目来源地址', blank=True, null=True, default=None)
    accepted = models.IntegerField(default=0, verbose_name='通过人数')
    submitted = models.IntegerField(default=0, verbose_name='提交人数')
    category = models.ManyToManyField(to=Category, verbose_name='类型',
                                      related_name='problem_category', blank=True)
    difficulty = models.IntegerField(verbose_name='难度等级')
    participants = models.IntegerField(verbose_name='参与分类的人数', default=0)
    pass_rate = models.DecimalField(verbose_name='通过率', default=0, decimal_places=2, max_digits=5)

    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.source)+str(self.problem_id))
        super(Problem, self).save(*args, **kwargs)


class SubmitAccount(models.Model):
    source = models.TextField(max_length=50, verbose_name='来源')
    account_id = models.TextField(max_length=30, verbose_name='账号')
    account_password = models.TextField(max_length=30, verbose_name='密码')

problems/views.py
import math
import re

import requests
from bs4 import BeautifulSoup
from django.core import serializers
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Problem, Category, SimpleCategory
from .utils.submit_code import HDUSubmit, main_function
from status.models import Status
from django.shortcuts import get_object_or_404
from django.db.models import Q
from uuslug import slugify


# Create your views here.


def problems(request):
    '''
    题目列表,这里的tag就是model中的category，status指的该用户是否AC
    :param request:
    :return:
    '''
    problem_list = Problem.objects.all()
    if request.session.get('not_first', False):
        difficulty = request.session.get('difficulty', '')
        difficulty = request.GET.get('difficulty', difficulty)
        difficulty_num = re.sub("\D", "", difficulty)
        tag = request.session.get('tag', '')
        tag = request.GET.get('tag', tag)
        status = request.session.get('status', '')
        status = request.GET.get('status', status)
    else:
        difficulty = '难度'
        tag = '标签'
        status = '状态'
        request.session['not_first'] = True
        request.session['difficulty'] = difficulty
        request.session['tag'] = tag
        request.session['status'] = status
    print('status', status)
    if status != '状态':
        if status == '已通过':
            status_list = Status.objects.filter(user=request.user)
            status_list = status_list.filter(result='Accepted')
            problem_list = [item.problem for item in status_list]
        if status == '未通过':
            status_list = Status.objects.filter(user=request.user)
            status_list = status_list.filter(~Q(result='Accepted'))
            problem_list = [item.problem for item in status_list]
        if status == '未做':
            problem_has_done = Status.objects.filter(user=request.user).values('problem')[0]
            print('problem_has_done', problem_has_done)
            # 还没写完呢
            pass
    if difficulty != '难度':
        problem_list = Problem.objects.filter(difficulty=difficulty_num)
    if tag != '标签':
        if tag == '未分类':
            problem_list = problem_list.filter(category=None)
        else:
            category = Category.objects.get(title=tag)
            problem_list = problem_list.filter(category=category)
    # 搜索实现
    search = request.GET.get('search', '')
    if search != '':
        problem_list = problem_list.filter(
            Q(title__contains=search) | Q(problem_id__contains=search))
    # 分页实现
    num = request.GET.get('num', 1)
    if num == '' or num == '0':
        num = 1
    paginator = Paginator(problem_list, 10)
    num = int(num)
    has_next = True
    if num > paginator.num_pages:
        num = paginator.num_pages
        has_next=False
    problem_list = paginator.page(num)
    begin = num - int(math.ceil(10.0 / 2))
    if begin < 1:
        begin = 1
    end = begin + 9
    if end > paginator.num_pages:
        end = paginator.num_pages
    if end <= 10:
        begin = 1
    else:
        begin = end - 9
    page_list = range(begin, end + 1)

    context = {
        'problem_list': problem_list,
        'difficulty': difficulty,
        'all_tag': Category.objects.values('title'),
        'tag': tag,
        'status': status,
        'num': num,
        'lnum': num - 1,
        'rnum': num + 1,
        'page_list': page_list,
        'search': search,
        'has_next': has_next,
    }
    return render(request, 'problems.html', context=context)


def problem_detail(request, slug):
    print("进入detail")
    '''
    题目的详细内容,
    post请求是返回答题结果
    :param request:
    :param slug:
    :return:
    '''
    if request.method == 'GET':
        problem = get_object_or_404(Problem, slug=slug)
        context = {
            'problem': problem,
            'category_list':Category.objects.all(),
        }
        return render(request, 'problem_detail.html', context=context)
    else:
        print("进入了post")
        source = request.POST.get('source', '')
        code = request.POST.get('code', '')
        language = request.POST.get('language', '')
        problem_id = request.POST.get('problem_id', '')
        print(source, code)
        problem = get_object_or_404(Problem, slug=slug)
        result = main_function(source, code, language, problem_id)
        print("result")
        print(result)
        if isinstance(result, str):
            return JsonResponse({"status": "submit failed"})
        else:
            if result.get('result') == "Accepted":
                problem.accepted += 1
                if Status.objects.filter(user=request.user).exists():
                    is_first = False
                else:
                    is_first = True
                if Status.objects.filter(result='Accepted', user=request.user, problem=problem).exists():
                    is_first_ac = False
                else:
                    is_first_ac = True
            status = Status.objects.create(result=result.get('result'),
                                           time=result.get('time', 0) if result.get('time', 0) != '' else 0,
                                           memory=result.get('memory', 0) if result.get('memory', 0) != '' else 0,
                                           code_length=result.get('code_length'),
                                           lang=result.get('lang'),
                                           # submit_time=result.get('submit_time'),
                                           user=request.user,
                                           problem=problem,
                                           is_first_ac=is_first_ac,
                                           is_first_submit=is_first,
                                           )
            status.save()
            problem.submitted += 1
            problem.pass_rate = problem.accepted / problem.submitted * 100
            problem.save()
            data = {
                "status": "success",
                "result": status.result,
            }
            return JsonResponse(data=data)


def modify_category_difficulty(request):
    print("进入modify")
    pk = request.GET.get("pk")
    problem = Problem.objects.filter(pk=pk).first()
    if problem:
        category_list = request.GET.getlist("category")
        difficulty = int(request.GET.get("difficulty"))
        # 题目分类修改
        '''
        这里修改思路是，获取用户提交的类别，然后对题目的SimpleCategory投票数加1或者新建，
        然后选择投票数最高的两位添加到题目上
        '''
        simple_categories = SimpleCategory.objects.filter(problem=problem)
        for category_vote in category_list:
            is_in = False
            for simple_category in simple_categories:
                if category_vote == simple_category.title:
                    simple_category.vote_number += 1
                    simple_category.save()
                    is_in = True
                    break
            if not is_in:
                SimpleCategory.objects.create(title=category_vote, vote_number=1, problem=problem).save()
        categories_vote_max = SimpleCategory.objects.filter(problem=problem).order_by('-vote_number')[:2]
        problem.category.clear()
        for item in categories_vote_max:
            category = get_object_or_404(Category, title=item.title)
            print(category)
            problem.category.add(category)
        # 题目难度修改
        num = problem.participants
        problem.difficulty = (num * problem.difficulty + difficulty) // (num + 1)
        problem.save()

        data = {
            "status": "success",
        }
        return JsonResponse(data=data)
    return JsonResponse(data={"status": "error"})


def problem_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    problem_list = Problem.objects.filter(category=category)
    context = {
        'problem_list': problem_list,
        'category': category,
    }
    return render(request, 'problem_category.html', context=context)


def problem_all_category(request):
    category_list = Category.objects.all()
    context = {
        'category_list': category_list,
    }
    return render(request, 'problem_all_category.html', context=context)


def problem_recommend(request):
    return render(request, 'problem_recommend.html')


def function_add_problem(search):

    url = 'http://acm.hdu.edu.cn/showproblem.php?pid=' + search
    html = requests.get(url)
    soup = BeautifulSoup(html.text, "lxml")
    i = 0
    a = soup.find_all('div', class_='panel_content')
    b = soup.find_all('span')[0].text
    b = re.split(r" |    ", b)

    title = soup.find(name='h1').string
    description = a[0].text
    input_description = a[1].text
    output_description = a[2].text
    sample_input = a[3].text
    sample_output = a[4].text
    tlimit = int(re.findall(r"\d+", b[2])[1])
    mlimit = int(re.findall(r"\d+", b[7])[1])

    low = 0.02549062736759782
    high = 0.7068466730954677
    parameter = (high - low) / 9
    rat = int(b[14]) / int(b[11])
    p = Problem(
        problem_id=search,
        time_limit=tlimit,
        memory_limit=mlimit,
        title=title,
        description=description,
        input_description=input_description,
        output_description=output_description,
        sample_input=sample_input,
        sample_output=sample_output,
        source='HDU',
        difficulty=int(math.ceil((high - rat) / parameter)),
    )
    p.save()
    return p


def problems_add(request):

    category_list = Category.objects.all()
    context = {
        'category_list': category_list,
    }
    if request.method == 'GET':

        return render(request, 'problem_add.html', context=context)
    else:
        search = request.POST.get('search')
        categories = requests.post.get('categories')
        problem = function_add_problem(search)  # 添加单个题目
        for i in categories:
            category = Category.objects.get(id=i)

problems/templates/problem_add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    增加题目
{% endblock %}
{% block content %}



{% endblock %}

problems/templates/problem_all_category.html
{% extends 'base.html' %}
{% load problem_tags %}
{% load static %}
{% block title %}
    题目分类
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}
{% block content %}
    {% for category in category_list %}
        {{ category.title }}
        {{ category.content }}
    {% endfor %}
{% endblock %}

problems/templates/problem_category.html
{% extends 'base.html' %}
{% load problem_tags %}
{% load static %}
{% block title %}
    题目分类
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/self_button.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <link rel="stylesheet" href="{% static 'css/problems_list.css' %}">
{% endblock %}
{% block content %}
    <section>
        <div class="container mt-3 mb-1" id="introduction">
            <div class="row">
                <div class="offset-sm-2 col-sm-8" id="detail">
                    <h1><b>{{ category.title }}</b></h1>
                    <p>
                        {{ category.content|safe }}
                    </p>
                </div>
            </div>
        </div>
        <!-- 题目列表begin -->
        <div class="container">
            <div class="card offset-sm-2 col-sm-8 mb-3">
                {% for problem in problem_list %}
                <div class="card-body py-3 row align-items-center">
                    <div class="col-1 text-muted text-center">
                        <!--fa-check是 √    fa-question是 ?-->
                        <i class="fa {% get_status problem%} fa-fw"></i>
                    </div>
                    <div class="col-2 text-muted text-center">{{ problem.problem_id }}</div>
                    <div class="col-4 text-muted"><a href="{% url 'problem:problem_detail' problem.slug %}">{{ problem.title }}</a></div>
                    <div class="col-1 text-muted">
                        <a href="http://acm.hdu.edu.cn/">
                            <button type="button" class="btn btn-sm btn-outline-success">{{ problem.source }}</button>
                        </a>
                    </div>
                    <div class="col-3 text-muted text-right">{{ problem.submitted }} | {{ problem.pass_rate }}%</div>
                </div>
                <hr class="m-0">
                {% endfor %}
                <hr class="m-0">
            </div>
        </div>
        <!-- 题目列表end -->
    </section>

{% endblock %}

problems/templates/problem_recommend.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    推荐题目
{% endblock %}
{% block content %}



{% endblock %}

problems/templates/problems.html
{% extends 'base.html' %}
{% load problem_tags %}
{% load static %}
{% block title %}
    problems
{% endblock %}
{% block head %}
{#    <link rel="stylesheet" href="{% static 'problems/css/problems_list.css' %}">#}
    <link rel="stylesheet" href="{% static 'problems/css/self_button.css' %}">
{#        <script type="text/javascript" src="{% static 'problems/problems_js.js' %}"></script>#}
{% endblock %}
{% block content %}
   <!-- https://bbbootstrap.com/snippets/forum-question-and-answer-listings-pagination-68897148 -->
    <div class="container-fluid mt-3">
        <form method="get" action="{% url 'problem:problem_list' %}" id="problem_selection_form">
            <input type="hidden" id="form_search" name="search">
            <input type="hidden" id="form_difficulty" name="difficulty" value="{{ difficulty }}">
            <input type="hidden" id="form_tag" name="tag" value="{{ tag }}">
            <input type="hidden" id="form_status" name="status" value="{{ status }}">
        </form>
        <div class="row">
            <!-- 搜索框begin -->
            <div class="col-5 p-0 ml-5 mb-3 d-flex flex-wrap justify-content-between align-items-center">
                <FORM action="/problems/" method="get">
                <input  name="search" type="text" class="form-control" placeholder="搜索题目 「名称、内容或编号」">
                <input type=submit value=search class=button40>
                </FORM>
            </div>
            <!-- 搜索框end -->

            <!-- 下拉列表begin-->
            <!-- 难度begin -->

            <div class="btn-group offset-3 col-1 align-items-center">
                <button type="button" class="btn btn-sm btn-tag dropdown-toggle"
                        data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" id="difficulty" form="problem_selection_form">
                    {{ difficulty }}
                </button>
                <div class="dropdown-menu" style="min-width: 0px">
                    <a class="dropdown-item" href="#"
                       style=" color: #9E9E9E;background-color: #F5FFC2;border-color: #FCFCFC;">level 0</a>
                    <a class="dropdown-item" href="#"
                       style="color: #787878;background-color: #E7FF6E;border-color: #FCFCFC;">level 1</a>
                    <a class="dropdown-item" href="#"
                       style="color: #474747;background-color: #E7FF6E;border-color: #FCFCFC;">level 2</a>
                    <a class="dropdown-item" href="#"
                       style="  color: #474747;background-color: #DBFF29;border-color: #FCFCFC;">level 3</a>
                    <a class="dropdown-item" href="#"
                       style="color: #474747;background-color: #D3F527;border-color: #FCFCFC;">level 4</a>
                    <a class="dropdown-item" href="#"
                       style="color: #2E2E2E;background-color: #ACF233;border-color: #FCFCFC;">level 5</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"
                       style="color: #FFFFFF;background-color: #85D92B;border-color: #FCFCFC;">level 6</a>
                    <a class="dropdown-item" href="#"
                       style="color: #FFFFFF;background-color: #77C425;border-color: #FCFCFC;">level 7</a>
                    <a class="dropdown-item" href="#"
                       style="color: #FFFFFF;background-color: #2AB040;border-color: #FCFCFC;">level 8</a>
                    <a class="dropdown-item" href="#"
                       style="color: #FFFFFF;background-color: #248C36;border-color: #FCFCFC;">level 9</a>
                </div>
            </div>
            <!-- 难度end -->

            <!-- tag begin-->
            <div class="btn-group col-1 align-items-center">
                <button type="button" class="btn btn-sm btn-tag dropdown-toggle"
                        data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" id="tag" form="problem_selection_form">
                    {{ tag }}
                </button>
                <div class="dropdown-menu" style="min-width: 0px">
                    {% for tag in all_tag %}
                    <a class="dropdown-item" href="#">{{ tag.title }}</a>
                    {% endfor %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'problem:problem_all_category' %}" style="color: #3192b2;background-color: #edfbff">更多标签</a>
                </div>
            </div>
            <!-- tag end-->

            <!-- 状态 begin-->
            <div class="btn-group col-1 align-items-center">
                <button type="button" class="btn btn-sm btn-tag dropdown-toggle"
                        data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" id="status">{{ status }}</button>
                <div class="dropdown-menu" style="min-width: 0px">
                    <a class="dropdown-item" href="#">所有题目</a>
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="#">已通过</a>
                    <a class="dropdown-item" href="#">未通过</a>
                    <a class="dropdown-item" href="#">未做</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'user:login' %}">请先登录</a>
                    {% endif %}
                </div>
            </div>
            <!-- 状态 end-->
            <!-- 下拉列表end-->
        </div>
        <!-- 题目列表begin -->
        <div class="card mb-3">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col-1 text-muted text-center">状态</div>
                    <div class="col-1 text-muted text-center">编号</div>
                    <div class="col-4 text-muted">题名</div>
                    <div class="col-1 text-muted text-center">来源</div>
                    <div class="col-1 text-muted text-center">解题数</div>
                    <div class="col-1 text-muted text-center">通过率</div>
                    <div class="col-2 text-muted text-center">标签</div>
                    <div class="col-1 text-muted text-center">难度等级</div>
                </div>
            </div>

            {#            一行#}
            <div id="problems">
            {% for problem in problem_list %}
            <div class="card-body py-3 row  align-items-center">
                <div class="col-1 text-muted text-center">
                    <!--fa-check是 √    fa-question是 ?-->
                    {% if user.is_authenticated %}
                    <a href="#">
                    <i class="fa {% get_status problem %} fa-fw">
                    </i>
                    </a>
                    {% endif %}
                </div>
                <div class="col-1 text-muted text-center">{{ problem.problem_id }}</div>
                <div class="col-4 text-muted"><a href="{% url 'problem:problem_detail' problem.slug %}">{{ problem.title }}</a></div>
                <div class="col-1 text-muted text-center">
                    <a href="{{ problem.source_url }}">
                        <button type="button" class="btn btn-sm btn-outline-success">{{ problem.source }}</button>
                    </a>
                </div>
                <div class="col-1 text-muted text-center">{{ problem.submitted }}</div>
                <div class="col-1 text-muted text-center">{{ problem.pass_rate }}%</div>
                <div class="col-2 text-muted text-center">
                    {% for category in problem.category.all %}
                     <a class="btn btn-sm btn-primary" href="{% url 'problem:problem_category' category.slug %}" role="button">{{ category }}</a>
                    {% endfor %}
                </div>
                <div class="col-1 text-muted text-center">
                    <button class="btn btn-sm btn-level{{ problem.difficulty }}" role="button" id="level-btn">level {{ problem.difficulty }}</button>
                </div>
            </div>
            <hr class="m-0">
            {% endfor %}
            </div>
            <hr class="m-0">
{#            一行结束#}

        </div>
        <!-- 题目列表end -->

        <!-- 分页器begin -->
        <nav>
            <ul class="pagination mb-5">
                <li class="page-item "><a class="page-link" href="/problems?search={{ search }}&&num={{lnum }}" data-abc="true">«</a></li>
                {% for n in page_list %}

                    {% if num == n %}
                        <li class="page-item active">
                            <a class="page-link" href="/problems?search={{ search }}&&num={{ n }}"
                               data-abc="true">{{ n}}</a>
                        </li>
                    {% else %}
                        <li class="page-item ">
                            <a class="page-link" href="/problems?search={{ search }}&&num={{n }}"
                               data-abc="true">{{ n }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if has_next %}
                <li class="page-item">
                    <a class="page-link" href="/problems?search={{ search }}&&num={{ rnum }}" data-abc="true">»</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="/problems?search={{ search }}&&num={{ rnum }}" data-abc="true">»</a>
{#                    弹框提示，最后一页了。#}
                </li>
                {% endif %}
            </ul>
        </nav>
        <!-- 分页器end -->
    </div>


{% endblock %}
{% block script %}
    <script type="text/javascript">
// 下拉框显示选中内容
$("#level-btn").click(function () {
      var selText = $(this).text();
      $("#form_difficulty").val(selText);
      $("#problem_selection_form").submit();

});
$(".dropdown-menu a").click(function(){
  var selText = $(this).text();
  $(this).parents('.btn-group').find('.dropdown-toggle').html(selText);
  if($(this).parents('.btn-group').find('.dropdown-toggle').attr("id")==="difficulty"){
      $("#form_difficulty").val(selText);
  }
  if($(this).parents('.btn-group').find('.dropdown-toggle').attr("id")==="tag"){
      if(selText=="更多标签"){
          return;
      }
    $("#form_tag").val(selText);
  }
  if($(this).parents('.btn-group').find('.dropdown-toggle').attr("id")==="status"){
      if(selText=="请先登录"){
          return;
      }
      $("#form_status").val(selText);

  }
  $("#problem_selection_form").submit();
});

</script>
{% endblock %}

problems/templates/submit.html
{% extends 'base.html' %}
{% block title %}
    problems
{% endblock %}
{% block content %}
    <h5>代码提交</h5>
            source = request.POST.get('source')
        code = request.POST.get('code')
        language = request.POST.get('language')
        problem_id = request.POST.get('problem_id')
        <form method="post" action="{% url 'problem:submit_code' %}">
            {% csrf_token %}
            来源<input type="text" name="source" >
            语言<input type="text" name="language">
            代码<textarea name="code">

            </textarea>
            <input type="hidden" name="problem_id" value="1000">
            <input type="submit" value="提交">
        </form>
{% endblock %}