mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import problems.urls
import users.urls
import status.urls
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('user/', include(users.urls)),
    path('status/',include(status.urls)),
    path('admin/', admin.site.urls),
    path('problems/', include(problems.urls)),
    path('captcha/', include('captcha.urls')),
    path('contact_us/', views.contact_us, name='contact_us'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

problems/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/11

from django.urls import path
from . import views
app_name = 'problem'
urlpatterns = [
    path('', views.problems, name='problem_list'),
    path('<slug:slug>/', views.problem_detail, name='problem_detail'),
    path('category',views.problem_all_category, name='problem_all_category'),
    path('category/<slug:slug>', views.problem_category, name='problem_category'),
    path('modify_category_difficulty', views.modify_category_difficulty, name='modify_category_difficulty'),
    path('recommend', views.problem_recommend, name='problem_recommend'),
    path('problem_add', views.problems_add, name='problem_add'),
]

status/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/13


from django.urls import path, include
from . import views
app_name = 'status'
urlpatterns = [
    path('', views.status, name='status'),
]

users/urls.py
#!python
# -*- encoding:utf-8 -*-
# Created by admin at 2020/9/13

from django.contrib import admin
from django.urls import path, include
import problems.views
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user_info, name='user_info'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgetpassword/', views.forget_password, name='forgetpassword'),
    path('resetpassword/<str:active_code>', views.reset_password, name='resetpassword'),
    path('terms/', views.terms, name='terms'),
    path('register/check_email/', views.check_email, name='check_email'),
    path('register/check_user/', views.check_user, name='check_user'),
    path('register/check_captcha/', views.check_captcha, name='check_captcha'),
    path('logout/', views.logout, name='logout'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('reset_pwd2/', views.reset_pwd2, name='reset_pwd2'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    关于我们
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/about_us.css' %}">
{% endblock %}
{% block content %}
    <section id="about_us" class="ml-5 pl-5">
        <div class="container">
            <div id="demo" class="carousel slide m-5 p-3" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-caption">
                            <p>If Shai Reznik's TDD videos don't convince you to add automated testing your code, I
                                don't
                                know what will.This was the very best explanation of frameworks for brginners that I've
                                ever
                                seen. </p> <img src="https://i.imgur.com/lE89Aey.jpg">
                            <div id="image-caption">Nick Doe</div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <p>If Shai Reznik's TDD videos don't convince you to add automated testing your code, I
                                don't
                                know what will.This was the very best explanation of frameworks for brginners that I've
                                ever
                                seen.
                            </p>
                            <img src="https://i.imgur.com/QptVdsp.jpg" class="img-fluid">
                            <div id="image-caption">Cromption Greves</div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <p>If Shai Reznik's TDD videos don't convince you to add automated testing your code, I
                                don't
                                know what will.This was the very best explanation of frameworks for brginners that I've
                                ever
                                seen.</p> <img src="https://i.imgur.com/jQWThIn.jpg" class="img-fluid">
                            <div id="image-caption">Harry Mon</div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#demo" data-slide="prev"> <i class='fas fa-arrow-left'></i> </a>
                <a
                        class="carousel-control-next" href="#demo" data-slide="next"> <i class='fas fa-arrow-right'></i>
                </a>
            </div>
        </div>
    </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">#}
{#    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>#}
    {% load static %}
    <script src="{% static 'lib/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'lib/js/popper.js' %}"></script>
    <script src="{% static 'lib/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.css' %}">
    <link rel="shortcut icon" href="{% static 'fonts/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/navigation.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/footer.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>

    {% include 'navigation.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    {% block script %}
    {% endblock %}

</body>
</html>

templates/base_deputy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">#}
    {% load static %}
    <script src="{% static 'lib/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'lib/js/popper.js' %}"></script>
    <script src="{% static 'lib/js/bootstrap.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'fonts/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/navigation.css' %}">
    <script src="{% static 'js/base.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/index.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/contact_us.html
{% extends "base.html" %}
{% load static %}

{% block title %}关于我们{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/contact_us.css' %}">
{% endblock %}
{% block content %}
    <section id="about_us" class="ml-5 pl-5">
        <div class="container">
            <div id="demo" class="carousel slide m-5 p-3" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-caption">
                            <p>You can follow our public WeChat account.</p>
                            <img src="/static/img/WeChat_Official_Account.png" class="img-fluid">
                            <div id="image-caption">微信公众号</div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <p>You can follow our Bilibili</p>
                            <img src="/static/img/WeChat_Official_Account.png" class="img-fluid">
                            <div id="image-caption">Bilibili</div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption">
                            <p>You can Email us</p>
                            <p class="width: 12rem;margin-top: 2rem">123456@163.com</p>
                            {#<img src="https://i.imgur.com/jQWThIn.jpg" class="img-fluid">#}
                            <div id="image-caption">Email</div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#demo" data-slide="prev"> <i class='fas fa-arrow-left'></i> </a>
                <a
                        class="carousel-control-next" href="#demo" data-slide="next"> <i class='fas fa-arrow-right'></i>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
{% endblock %}

templates/footer.html
<!-----------------------尾部begin------------------------------>
<footer id="index_footer" class="pt-2" style="border: 1px solid #eee">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 ml-5">
                <ul>
                    <li>© 东华大学ACM题集与分析项目组 版权所有</li>
                    <li class="text-muted small">
                        <span>沪ICP备********号</span>
                        <span> | </span>
                        <span>沪公网安备********号</span>
                    </li>
                </ul>
            </div>
            <div class="offset-1 col-4 mr-5 d-flex justify-content-end align-items-end">
                <ul>
                    <li>
                        <a href="{% url 'about' %}">关于我们</a>
                        <span> | </span>
                        <a href="{% url 'contact_us' %}">联系我们</a>
                    </li>
                    <li class="text-muted small d-flex align-items-center pull-right"
                        style="font-family: 'Microsoft YaHei UI'">
                        <img src="/static/img/cn.svg" height="16">
                        <span>&ensp;Coding in China</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-----------------------尾部end-------------------------------->
{#<div class="col-lg-4 d-none d-lg-block">#}
{#    <div class="row d-flex justify-content-center align-items-center">#}
{#        <ul class="offset-lg-2 col-lg-4">#}
{#            <li><a href="{% url 'about' %}">关于我们</a></li>#}
{#        </ul>#}
{#    </div>#}
{#</div>#}
{#<div class="col-6 col-lg-5 d-none d-md-block text-center">#}
{#    <h6>公司地址:上海市松江区松江大学城</h6>#}
{#    <h6>联系电话:0598-88888888</h6>#}
{#    <h6>地址邮箱: 123456@123.com</h6>#}
{#</div>#}
{#<div class="col-lg-3 text-center d-sm-block d-md-none d-lg-block">#}
{#    <a href="{% url 'contact_us' %}">#}
{#        <h6 class="text-muted">联系我们:</h6>#}
{#        <img src="/static/img/weixin-h.png" width="40" class="mr-2" alt="">#}
{#        <img src="/static/img/xinlang-h.png" width="40" alt="">#}
{#    </a>#}
{#</div>#}

templates/navigation.html
{% load static %}
<header id="index_header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand d-flex justify-content-center align-items-center" href="#">
                <img src="{% static 'img/TFlogo2.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#index_navbar_sc"
                    aria-controls="index_navbar_sc" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="index_navbar_sc">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">首页<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'problem:problem_list' %}">题目列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'problem:problem_recommend'  %}">推荐题目</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'status:status' %}">状态</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:questionnaire' %}">问卷调查</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            下拉列表
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">表项1</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">表项2</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">表项3</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 justify-content-center align-items-center">
                     {% if not user.is_authenticated %}
                        <a class="btn btn-outline-primary btn-sm" href="{% url 'user:register' %}">现在注册</a>
                        <a class="btn btn-outline-info btn-sm ml-2" href="{% url 'user:login' %}">立即登陆</a>
                    {% else %}

                         <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{% url 'user:user_info' %}">个人资料</a>
                                {% if perms.foo %}
                                <a class="dropdown-item" href="#">添加题目</a>
                                {% endif %}
                              <a class="dropdown-item" href="#">参与的讨论</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出登录</a>
                            </div>
                        </div>
                    {% endif %}
                    <!--
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                     -->

                </form>
            </div>
        </div>
    </nav>
</header>